### ISSUE TITLE
How to use ninja -t recompact

### ISSUE THREAD

**Issue by feliwir** [nico/buildbloat#1]
I am having the issue that i seem to have duplicate entries in my ninja_log file, so i tried running `ninja -t recompact` as suggested here, but it does absolutly nothing. There is little to no information on how to use that tool. Any suggestions?

The exact error happens when running **webtreemap**:
```
Error: duplicate path  NaN
    at _loop_1 (/usr/local/lib/node_modules/webtreemap/build/tree.js:20:27)
    at Object.treeify (/usr/local/lib/node_modules/webtreemap/build/tree.js:27:13)
    at treeFromLines (/usr/local/lib/node_modules/webtreemap/build/cli.js:83:21)
    at /usr/local/lib/node_modules/webtreemap/build/cli.js:128:31
    at step (/usr/local/lib/node_modules/webtreemap/build/cli.js:33:23)
    at Object.next (/usr/local/lib/node_modules/webtreemap/build/cli.js:14:53)
    at fulfilled (/usr/local/lib/node_modules/webtreemap/build/cli.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7
```

**Comment by asatara** [comment]
buildbloat was designed to work with webtreeapp v1. You're trying to use webtreeapp v2 which uses a different format.

Here's a simple python script to convert the .ninja_log file to the webtreeapp v2 format:
`with open('.ninja_log', 'r') as fp:
    line = fp.readline()
    line = fp.readline()
    while line:
        fields = line.split()
        duration = int(fields[1]) - int(fields[0])
        print("{} {}").format(duration, fields[3])
        line = fp.readline()`

**Comment by Warchant** [comment]
```
#!/usr/bin/python3
with open('.ninja_log', 'r') as fp: 
    line = fp.readline() 
    line = fp.readline() 
    while line:
        fields = line.split() 
        duration = int(fields[1]) - int(fields[0]) 
        print("{} {}".format(duration, fields[3]))
        line = fp.readline()

```
